set CUR_DRIVE=%~d0
set CUR_DIR=%~dp0
set VC_ENV="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
set VC_CMAKE="Visual Studio 15 2017 Win64"
set MONGOC_NAME=mongo-c-driver-1.14.0.7z
set MONGOC_ARC=mongo-c-driver-1.14.0
set MONGOC_DIR=mongo-c-driver-1.14.0
set MONGO_NAME=mongo-cxx-driver-r3.4.0.7z
set MONGO_ARC=mongo-cxx-driver-r3.4.0
set MONGO_DIR=mongo-cxx-driver-r3.4.0
set C_DIR=mongo-c-driver
set CXX_DIR=mongo-cxx-driver
set CX_DIR=C:\develop\libraries\script\mongo\mongo-c-driver
set BOOST_DIR=C:\develop\includes
set CX_DIR1=/home/zyh/mongo-c-driver
set BOOST_DIR1=/home/zyh/boost_1_70_0
set PRJ_CFG=Debug
set LINUX_IP=192.168.0.105
set LINUX_NAME=zyh
set LINUX_PWD=zyouhua99